# Generated by Django 2.2.4 on 2021-05-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20210501_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='updated_at',
            new_name='date_granted',
        ),
    ]
